spring.application.name=backend_usersapp

# URL de conexión a la base de datos MySQL.
spring.datasource.url=jdbc:mysql://localhost:3306/db_users_springboot
# Usuario para acceder a la base de datos.
spring.datasource.username=root
# Contraseña del usuario de la base de datos.
spring.datasource.password=root123
# Clase del driver JDBC para conectar con MySQL.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Muestra las consultas SQL generadas por JPA/Hibernate en consola.
spring.jpa.show-sql=true
# Configura el nivel de logs para ver las consultas SQL de Hibernate.
logging.level.org.hibernate.SQL=DEBUG
# Crear lastablas automáticamente según las entidades JPA al iniciar la aplicación.
spring.jpa.hibernate.ddl-auto=update

# api en postman: localhost:8080/api/users
# para conectar con mysql: docker exec -it mysql-spring mysql -u root -p
